/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packageRegist;

/**
 *
 * @author ASUS
 */
import packageKoneksi.config;
import packageLogin.JFrameLogin;
import packageRegist.JFrameRegist;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class JFrameRegist extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRegist
     */
    public JFrameRegist() {
        initComponents();

    }
    Connection cn = packageKoneksi.config.BukaKoneksi();

    public Statement st;
    public ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void BersihRegist (){
      t_idpegawai.setText("");
      t_name.setText("");
      t_phonenumber.setText("");
      t_email.setText("");
      t_address.setText("");
      jstatus.setSelectedIndex(-1);
      t_username.setText("");
      t_password.setText("");
      
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_phonenumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jstatus = new rojerusan.RSComboMetro();
        jLabel9 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_password = new javax.swing.JPasswordField();
        btn_regist = new rojerusan.RSMaterialButtonRectangle();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t_idpegawai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(214, 220, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Join With Us !");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 160, 20));

        jLabel4.setText("Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        t_name.setBackground(new java.awt.Color(173, 226, 206));
        t_name.setForeground(new java.awt.Color(153, 153, 153));
        t_name.setText(" enter your name..");
        t_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        t_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_nameFocusLost(evt);
            }
        });
        jPanel2.add(t_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 40));

        jLabel5.setText("Phone Number");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        t_phonenumber.setBackground(new java.awt.Color(173, 226, 206));
        t_phonenumber.setForeground(new java.awt.Color(153, 153, 153));
        t_phonenumber.setText(" enter phone number..");
        t_phonenumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        t_phonenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_phonenumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_phonenumberFocusLost(evt);
            }
        });
        jPanel2.add(t_phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 170, 40));

        jLabel7.setText("Email");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        t_email.setBackground(new java.awt.Color(173, 226, 206));
        t_email.setForeground(new java.awt.Color(153, 153, 153));
        t_email.setText(" enter email..");
        t_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        t_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_emailFocusLost(evt);
            }
        });
        jPanel2.add(t_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 170, 40));

        jLabel6.setText("Address");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        t_address.setBackground(new java.awt.Color(173, 226, 206));
        t_address.setForeground(new java.awt.Color(153, 153, 153));
        t_address.setText(" enter address..");
        t_address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        t_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_addressFocusLost(evt);
            }
        });
        t_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_addressActionPerformed(evt);
            }
        });
        jPanel2.add(t_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 170, 40));

        jLabel8.setText("Status");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        jstatus.setBackground(new java.awt.Color(173, 226, 206));
        jstatus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        jstatus.setForeground(new java.awt.Color(153, 153, 153));
        jstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dokter", "Apoteker" }));
        jstatus.setColorArrow(new java.awt.Color(0, 102, 102));
        jstatus.setColorFondo(new java.awt.Color(173, 226, 206));
        jstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstatusActionPerformed(evt);
            }
        });
        jPanel2.add(jstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 200, 40));

        jLabel9.setText("Username");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        t_username.setBackground(new java.awt.Color(173, 226, 206));
        t_username.setForeground(new java.awt.Color(153, 153, 153));
        t_username.setText(" enter username..");
        t_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        jPanel2.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 200, 40));

        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        t_password.setBackground(new java.awt.Color(173, 226, 206));
        t_password.setText("isipassword");
        t_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        t_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordFocusLost(evt);
            }
        });
        jPanel2.add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 200, 40));

        btn_regist.setBackground(new java.awt.Color(0, 102, 102));
        btn_regist.setText("Register");
        btn_regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registActionPerformed(evt);
            }
        });
        jPanel2.add(btn_regist, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 140, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packageRegist/NewUser.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 90));

        jLabel12.setText("Id Pegawai");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        t_idpegawai.setBackground(new java.awt.Color(173, 226, 206));
        t_idpegawai.setForeground(new java.awt.Color(153, 153, 153));
        t_idpegawai.setText(" enter id pegawai...");
        t_idpegawai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        t_idpegawai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_idpegawaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_idpegawaiFocusLost(evt);
            }
        });
        jPanel2.add(t_idpegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 180, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img_regist.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, -170, -1, 700));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 750, 530));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packageRegist/close.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registActionPerformed
       String id_pegawai = t_idpegawai.getText();
       String name = t_name.getText();
       String phonenumber = t_phonenumber.getText();
       String email = t_email.getText();
       String address = t_address.getText();
       String status = jstatus.getSelectedItem().toString();
       String username = t_username.getText();
       String password = t_password.getText();
       
        if(id_pegawai.isEmpty() || name.isEmpty() || phonenumber.isEmpty() || email.isEmpty() || address.isEmpty() || status.isEmpty() || username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            // Query untuk insert data ke dalam tabel apoteker dengan menggunakan data dari klinik_user
            String sql = "INSERT INTO klinik_user (id_pegawai, nama, telepon, email, alamat, status, username, password) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

            Connection cn = config.BukaKoneksi();
            PreparedStatement pstmt = cn.prepareStatement(sql);
            pstmt.setString(1, id_pegawai);
            pstmt.setString(2, name);
            pstmt.setString(3, phonenumber);
            pstmt.setString(4, email);  
            pstmt.setString(5, address);
            pstmt.setString(6, status); 
            pstmt.setString(7, username);
            pstmt.setString(8, password); // Ubah sesuai dengan kolom primary key yang sesuai di klinik_user

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Anda Berhasil di Simpan");
            BersihRegist();
            this.dispose();
            JFrameLogin loginbaru = new JFrameLogin();
            loginbaru.show();
           
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_registActionPerformed

     private String getTableNameByStatus(String status) {
        switch (status) {
            case "Admin":
                return "tabel_admin";
            case "Dokter":
                return "dokter";
            case "Apoteker":
                return "apoteker";
            default:
                return "tabel_default";
        }
    }
    
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void t_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nameFocusGained
        String name = t_name.getText();
        if(name.equals(" enter your name..")){
            t_name.setText("");
        }
    }//GEN-LAST:event_t_nameFocusGained

    private void t_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nameFocusLost
        String name = t_name.getText();
        if(name.equals("") ||name.equals(" enter your name..")) {
            t_name.setText(" enter your name..");
        }
    }//GEN-LAST:event_t_nameFocusLost

    private void t_phonenumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_phonenumberFocusGained
        String number = t_phonenumber.getText();
        if(number.equals(" enter phone number..")){
            t_phonenumber.setText("");
        }
    }//GEN-LAST:event_t_phonenumberFocusGained

    private void t_phonenumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_phonenumberFocusLost
        String number = t_phonenumber.getText();
        if(number.equals("") ||number.equals(" enter phone number..")) {
            t_phonenumber.setText(" enter phone number..");
        }
    }//GEN-LAST:event_t_phonenumberFocusLost

    private void t_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_addressFocusGained
        String address = t_address.getText();
        if(address.equals(" enter address..")){
            t_address.setText("");
        }
    }//GEN-LAST:event_t_addressFocusGained

    private void t_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_addressFocusLost
        String address = t_address.getText();
        if(address.equals("") ||address.equals(" enter address..")) {
            t_address.setText(" enter address..");
        }
    }//GEN-LAST:event_t_addressFocusLost

    private void t_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_emailFocusGained
        String email = t_email.getText();
        if(email.equals(" enter email..")){
            t_email.setText("");
        }
    }//GEN-LAST:event_t_emailFocusGained

    private void t_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_emailFocusLost
        String email = t_email.getText();
        if(email.equals("") ||email.equals(" enter email..")) {
            t_email.setText(" enter email..");
        }
    }//GEN-LAST:event_t_emailFocusLost

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        String usernamee = t_username.getText();
        if(usernamee.equals(" enter username..")){
            t_username.setText("");
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
        String usernamee = t_username.getText();
        if(usernamee.equals("") ||usernamee.equals(" enter username..")) {
            t_username.setText(" enter username..");
        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusGained
        String password = t_password.getText();
        if(password.equals("isipassword")){
            t_password.setText("");
        }
    }//GEN-LAST:event_t_passwordFocusGained

    private void t_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusLost
        String password = t_password.getText();
        if(password.equals("") ||password.equals("isipassword")) {
           t_password.setText("isipassword");
        }
    }//GEN-LAST:event_t_passwordFocusLost

    private void t_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_addressActionPerformed

    private void jstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstatusActionPerformed

    private void t_idpegawaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idpegawaiFocusGained
        String id_pegawai = t_idpegawai.getText();
        if(id_pegawai.equals(" enter id pegawai...")){
            t_idpegawai.setText("");
        }
    }//GEN-LAST:event_t_idpegawaiFocusGained

    private void t_idpegawaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idpegawaiFocusLost
       String id_pegawai = t_idpegawai.getText();
        if(id_pegawai.equals("") ||t_idpegawai.equals(" enter id pegawai...")) {
           t_idpegawai.setText(" enter id pegawai...");
        }
    }//GEN-LAST:event_t_idpegawaiFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRegist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_regist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSComboMetro jstatus;
    private javax.swing.JTextField t_address;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_idpegawai;
    private javax.swing.JTextField t_name;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_phonenumber;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables
}
