/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packageapoteker;


import packagehome.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import packageKoneksi.config;
import packageLogin.JFrameLogin;
import packagehome.JFrameclinicdata;
import packagehome.JFramehome;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import packageapoteker.JFrameclinicdataApoteker;

public class JFrameuserclinicApoteker extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    Connection cn = packageKoneksi.config.BukaKoneksi();

    
    /**
     * Creates new form JFramehome
     */
    public JFrameuserclinicApoteker() {
        initComponents();
        
       Tampildatapotekeruser();
       TampilAllUser();
        
        
        Submenuuser.setVisible(true);
        paneluser.setVisible(true);
        panel_apoteker.setVisible(false);
        panel_alluser.setVisible(false);
        
    }
    

    
   
    
   
   
    
    private void Tampildatapotekeruser(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM apoteker");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Apoteker");
            model.addColumn("Nama");
            model.addColumn("Telepon");
            model.addColumn("Alamat");
            model.addColumn("Email");
            model.addColumn("Shift");
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                  rs.getString("id_pegawai"),
                  rs.getString("nama"),
                  rs.getString("telepon"),
                  rs.getString("alamat"),
                  rs.getString("email"),
                  rs.getString("shift"),
                };
                model.addRow(data);
               tbl_apotekeruser.setModel(model);
            }
        } catch (Exception e) {
        }
    }
    
    private void TampilAllUser(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM klinik_user");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Id Pegawai");
            model.addColumn("Nama");
            model.addColumn("Telepon");
            model.addColumn("Email");
            model.addColumn("Alamat");
            model.addColumn("Status");
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                  rs.getString("id_pegawai"),
                  rs.getString("nama"),
                  rs.getString("telepon"),
                  rs.getString("email"),
                  rs.getString("alamat"),
                  rs.getString("status"),
                };
                model.addRow(data);
                TableallUser.setModel(model);
            }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_home = new rojerusan.RSButtonIconD();
        btn_data = new rojerusan.RSButtonIconD();
        btn_report = new rojerusan.RSButtonIconD();
        btn_user = new rojerusan.RSButtonIconD();
        btn_us = new rojerusan.RSButtonIconD();
        btn_logout = new rojerusan.RSButtonIconD();
        jPanel3 = new javax.swing.JPanel();
        Submenuuser = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        panel_alluser = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableallUser = new javax.swing.JTable();
        panel_apoteker = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        t_idapotekeruser = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        t_shiftuser = new javax.swing.JComboBox<>();
        btnsubmitapoteker = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_apotekeruser = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        paneluser = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clinic.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("STKaiti", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome to Healthy-Connect");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 490, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 180));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(165, 165, 165));
        btn_home.setForeground(new java.awt.Color(0, 0, 0));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homee.png"))); // NOI18N
        btn_home.setText("Home ");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 51));

        btn_data.setBackground(new java.awt.Color(165, 165, 165));
        btn_data.setForeground(new java.awt.Color(0, 0, 0));
        btn_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/data.png"))); // NOI18N
        btn_data.setText("Clinic Data");
        btn_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataActionPerformed(evt);
            }
        });
        jPanel2.add(btn_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 50));

        btn_report.setBackground(new java.awt.Color(165, 165, 165));
        btn_report.setForeground(new java.awt.Color(0, 0, 0));
        btn_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report.png"))); // NOI18N
        btn_report.setText("Report Clinic");
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        jPanel2.add(btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 50));

        btn_user.setBackground(new java.awt.Color(165, 165, 165));
        btn_user.setForeground(new java.awt.Color(0, 0, 0));
        btn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/i_user.png"))); // NOI18N
        btn_user.setText("User Clinic");
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });
        jPanel2.add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, 50));

        btn_us.setBackground(new java.awt.Color(165, 165, 165));
        btn_us.setForeground(new java.awt.Color(0, 0, 0));
        btn_us.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/us.png"))); // NOI18N
        btn_us.setText("About US");
        btn_us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usActionPerformed(evt);
            }
        });
        jPanel2.add(btn_us, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, 50));

        btn_logout.setBackground(new java.awt.Color(165, 165, 165));
        btn_logout.setForeground(new java.awt.Color(0, 0, 0));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 200, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1250, 50));

        jPanel3.setBackground(new java.awt.Color(124, 192, 192));
        jPanel3.setForeground(new java.awt.Color(124, 192, 192));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Submenuuser.setBackground(new java.awt.Color(0, 102, 102));
        Submenuuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        Submenuuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmenuuserMouseEntered(evt);
            }
        });
        Submenuuser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label3.setFont(new java.awt.Font("Lucida Fax", 0, 13)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/apoteker.png"))); // NOI18N
        label3.setText("Pharmacist's User");
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
        });
        Submenuuser.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        label4.setFont(new java.awt.Font("Lucida Fax", 0, 13)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/alluser.png"))); // NOI18N
        label4.setText("All User Data");
        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4MouseClicked(evt);
            }
        });
        Submenuuser.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jPanel3.add(Submenuuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 200, 80));

        panel_alluser.setBackground(new java.awt.Color(124, 192, 192));
        panel_alluser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel15.setText("All Data User");
        panel_alluser.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        TableallUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Pegawai", "Nama", "Telepon", "Email", "Alamat", "Status"
            }
        ));
        TableallUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableallUserMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TableallUser);

        panel_alluser.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 1070, -1));

        jPanel3.add(panel_alluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 550));

        panel_apoteker.setBackground(new java.awt.Color(124, 192, 192));
        panel_apoteker.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setText("Id Apoteker :");
        panel_apoteker.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        t_idapotekeruser.setBackground(new java.awt.Color(124, 192, 192));
        t_idapotekeruser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        panel_apoteker.add(t_idapotekeruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 250, 30));

        jLabel27.setText("Shift :");
        panel_apoteker.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        t_shiftuser.setBackground(new java.awt.Color(124, 192, 192));
        t_shiftuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi ( 08:00 pagi - 17:00 sore)", "Malam ( 17:00 sore - 08:00 pagi)" }));
        t_shiftuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 102, 102)));
        panel_apoteker.add(t_shiftuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 250, 40));

        btnsubmitapoteker.setBackground(new java.awt.Color(0, 102, 102));
        btnsubmitapoteker.setText("Submit");
        btnsubmitapoteker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitapotekerActionPerformed(evt);
            }
        });
        panel_apoteker.add(btnsubmitapoteker, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 130, 40));

        tbl_apotekeruser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Apoteker", "Nama", "Telepon", "Alamat", "Email", "Shift"
            }
        ));
        jScrollPane3.setViewportView(tbl_apotekeruser);

        panel_apoteker.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 780, -1));

        jLabel30.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel30.setText("Apoteker USER");
        panel_apoteker.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        jPanel3.add(panel_apoteker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 550));

        paneluser.setBackground(new java.awt.Color(124, 192, 192));
        paneluser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(paneluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 550));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1250, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
      JFramehomeapoteker homeapo = new JFramehomeapoteker();
      homeapo.show();
      
      this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
      JFrameuserclinicApoteker userclinicapo = new JFrameuserclinicApoteker();
      userclinicapo.show();
      this.dispose();
      Submenuuser.setVisible(!Submenuuser.isVisible());
    }//GEN-LAST:event_btn_userActionPerformed

    private void btn_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataActionPerformed
        JFrameclinicdataApoteker clinicdataapo = new JFrameclinicdataApoteker();
        clinicdataapo.show();
        Submenuuser.setVisible(!Submenuuser.isVisible());
        this.dispose();
    }//GEN-LAST:event_btn_dataActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
      JFrameLogin login = new JFrameLogin();
      login.show();
      
      this.dispose();
      JOptionPane.showMessageDialog(null, "Logout Success");
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
     dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btn_usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usActionPerformed
      JFrameAboutUsApoteker aboutclinicapo = new JFrameAboutUsApoteker();
      aboutclinicapo.show();
      Submenuuser.setVisible(!Submenuuser.isVisible());
      this.dispose();
    }//GEN-LAST:event_btn_usActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
       JFramereportclinicApoteker reportclinicapo = new JFramereportclinicApoteker();
       reportclinicapo.show();
       Submenuuser.setVisible(!Submenuuser.isVisible());
       this.dispose();
    }//GEN-LAST:event_btn_reportActionPerformed

    private void btnsubmitapotekerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitapotekerActionPerformed
        String idapoteker = t_idapotekeruser.getText();
        String selectedshift = (String) t_shiftuser.getSelectedItem();

        if(idapoteker.isEmpty() || selectedshift.isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua Kolom Harus Diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Query untuk insert data ke dalam tabel apoteker dengan menggunakan data dari klinik_user
            String sql = "INSERT INTO apoteker (id_pegawai, nama, telepon, alamat, email, shift) " +
            "SELECT ?, nama, telepon, alamat, email, ? FROM klinik_user WHERE id_pegawai = ?";

            Connection cn = config.BukaKoneksi();
            PreparedStatement pstmt = cn.prepareStatement(sql);
            pstmt.setString(1, idapoteker);
            pstmt.setString(2, selectedshift);
            pstmt.setString(3, idapoteker);  // Ubah sesuai dengan kolom primary key yang sesuai di klinik_user

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Anda Berhasil di Simpan");
            Tampildatapotekeruser(); 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsubmitapotekerActionPerformed

    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
        panel_apoteker.setVisible(true);
        paneluser.setVisible(false);
        panel_alluser.setVisible(false);
        
        Submenuuser.setVisible(false);
    }//GEN-LAST:event_label3MouseClicked

    private void label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseClicked
        panel_alluser.setVisible(true);
        panel_apoteker.setVisible(false);
        paneluser.setVisible(false);
        
        Submenuuser.setVisible(false);
    }//GEN-LAST:event_label4MouseClicked

    private void SubmenuuserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmenuuserMouseEntered
        Submenuuser.setVisible(true);
    }//GEN-LAST:event_SubmenuuserMouseEntered

    private void TableallUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableallUserMouseClicked


    }//GEN-LAST:event_TableallUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameuserclinicApoteker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameuserclinicApoteker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameuserclinicApoteker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameuserclinicApoteker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameuserclinicApoteker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Submenuuser;
    private javax.swing.JTable TableallUser;
    private rojerusan.RSButtonIconD btn_data;
    private rojerusan.RSButtonIconD btn_home;
    private rojerusan.RSButtonIconD btn_logout;
    private rojerusan.RSButtonIconD btn_report;
    private rojerusan.RSButtonIconD btn_us;
    private rojerusan.RSButtonIconD btn_user;
    private rojerusan.RSMaterialButtonRectangle btnsubmitapoteker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JPanel panel_alluser;
    private javax.swing.JPanel panel_apoteker;
    private javax.swing.JPanel paneluser;
    private javax.swing.JTextField t_idapotekeruser;
    private javax.swing.JComboBox<String> t_shiftuser;
    private javax.swing.JTable tbl_apotekeruser;
    // End of variables declaration//GEN-END:variables
}
